In [1]:
import pandas as pd

In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('Iris.csv')

In [4]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [6]:
df = df.iloc[:,1:]

In [7]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [8]:
x = df.drop('Species',axis = 1)
y = df['Species']

In [9]:
y.sample(10)

29         Iris-setosa
108     Iris-virginica
21         Iris-setosa
69     Iris-versicolor
11         Iris-setosa
75     Iris-versicolor
104     Iris-virginica
46         Iris-setosa
33         Iris-setosa
61     Iris-versicolor
Name: Species, dtype: object

In [10]:
def converter(y):
    if y == 'Iris-setosa':
        return 0
    if y == 'Iris-versicolor':
        return 1
    if y == 'Iris-virginica':
        return 2

In [11]:
y_new = y.apply(converter)

In [12]:
y_new

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

In [13]:
X_train,X_test,y_train,y_test = train_test_split(x,y_new,test_size = 0.2,random_state = 0)

In [14]:
X_train

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
137            6.4           3.1            5.5           1.8
84             5.4           3.0            4.5           1.5
27             5.2           3.5            1.5           0.2
127            6.1           3.0            4.9           1.8
132            6.4           2.8            5.6           2.2
..             ...           ...            ...           ...
9              4.9           3.1            1.5           0.1
103            6.3           2.9            5.6           1.8
67             5.8           2.7            4.1           1.0
117            7.7           3.8            6.7           2.2
47             4.6           3.2            1.4           0.2

[120 rows x 4 columns]

In [15]:
X_test

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
114            5.8           2.8            5.1           2.4
62             6.0           2.2            4.0           1.0
33             5.5           4.2            1.4           0.2
107            7.3           2.9            6.3           1.8
7              5.0           3.4            1.5           0.2
100            6.3           3.3            6.0           2.5
40             5.0           3.5            1.3           0.3
86             6.7           3.1            4.7           1.5
76             6.8           2.8            4.8           1.4
71             6.1           2.8            4.0           1.3
134            6.1           2.6            5.6           1.4
51             6.4           3.2            4.5           1.5
73             6.1           2.8            4.7           1.2
54             6.5           2.8            4.6           1.5
63             6.1           2.9            4.7           1.4
37             4.9           3.1            1.5           0.1
78             6.0           2.9            4.5           1.5
90             5.5           2.6            4.4           1.2
45             4.8           3.0            1.4           0.3
16             5.4           3.9            1.3           0.4
121            5.6           2.8            4.9           2.0
66             5.6           3.0            4.5           1.5
24             4.8           3.4            1.9           0.2
8              4.4           2.9            1.4           0.2
126            6.2           2.8            4.8           1.8
22             4.6           3.6            1.0           0.2
44             5.1           3.8            1.9           0.4
97             6.2           2.9            4.3           1.3
93             5.0           2.3            3.3           1.0
26             5.0           3.4            1.6           0.4

In [16]:
y_test

114    2
62     1
33     0
107    2
7      0
100    2
40     0
86     1
76     1
71     1
134    2
51     1
73     1
54     1
63     1
37     0
78     1
90     1
45     0
16     0
121    2
66     1
24     0
8      0
126    2
22     0
44     0
97     1
93     1
26     0
Name: Species, dtype: int64

In [17]:
y_train

137    2
84     1
27     0
127    2
132    2
      ..
9      0
103    2
67     1
117    2
47     0
Name: Species, Length: 120, dtype: int64

In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
lr = LinearRegression()

In [20]:
pred = lr.fit(X_train,y_train)

In [21]:
y_pred = pred.predict(X_test)

In [22]:
y_pred

array([ 2.06703909,  0.96488074, -0.14594224,  1.81373137, -0.03780827,
        2.26136881, -0.02684168,  1.3195563 ,  1.28300114,  1.11288966,
        1.54909827,  1.30153965,  1.2127103 ,  1.32986888,  1.33047544,
       -0.07605449,  1.35607655,  1.21563955,  0.0373887 , -0.02449662,
        1.79885764,  1.3946086 ,  0.07528911,  0.02303999,  1.59033372,
       -0.11806588,  0.14915066,  1.1671282 ,  0.90650885,  0.10691577])

In [23]:
y_pred = y_pred.astype(int)
y_pred

array([2, 0, 0, 1, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0])

In [24]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8

In [25]:
from sklearn.tree import DecisionTreeRegressor

In [26]:
dtr = DecisionTreeRegressor()

In [27]:
dtr_pred = dtr.fit(X_train,y_train)

In [28]:
y_pred_2 = dtr_pred.predict(X_test)

In [29]:
y_pred_2

array([2., 1., 0., 2., 0., 2., 0., 1., 1., 1., 2., 1., 1., 1., 1., 0., 1.,
       1., 0., 0., 2., 1., 0., 0., 2., 0., 0., 1., 1., 0.])

In [30]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred_2)

1.0

In [31]:
import pickle

In [35]:
pickle.dump(dtr_pred,open('flower.pkl','wb'))